### PR TITLE
Project list

### PR DESCRIPTION
**Pull request by a-moses**
add project list return  title .

### CODE REVIEW

**Comment by nonZero** [comment]
Hi!

Nice to meet you a-moses!

I don't understand what's the point in this pull request.
Can you elaborate please?

Thanks,
Udi

**Comment by a-moses** [comment]
Hi Udi

The project title looks like the subject of the page only, and not as url to return back .
so for easy navigation i added the PR but if not, 

Please consider just add any icon near the project title (like  glyphicon-menu-hamburger).

Thank you anyway :)

**Comment by nonZero** [comment]
The line you changed is our breadcrumbs:
http://ui-patterns.com/patterns/Breadcrumbs
http://getbootstrap.com/components/#breadcrumbs
We are using the breadcrumbs metaphor/pattern/component in many places in our non-public website - take a look around the code.
In the public website this page is (currently) the only visible instance of the breadcrumbs, and might be somewhat confusing - but I do think it is descriptive and concise.
Any other suggestion?

**Comment by a-moses** [comment]
Now I understand the considerations

Thanks for your patience

**Pull request closed without merging**
